services:
    spotify.session_handler:
        class: Bench1ps\Spotify\Session\SessionHandler

    spotify.authorization:
        class: Bench1ps\Spotify\Authorization\Authorization
        arguments:
            - client_id: "%spotify.client_id%"
              client_secret: "%spotify.client_secret%"
              redirect_uri: "%spotify.client_redirect_uri%"
              base_url: "https://accounts.spotify.com"
              proxy: "%spotify.proxy%"
            - "@spotify.session_handler"

    spotify.api:
        class: Bench1ps\Spotify\API\API
        arguments:
            - base_url: "https://api.spotify.com"
              proxy: "%spotify.proxy%"
            - "@spotify.session_handler"